services:
  - type: web
    name: bollywood-classifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server/server.py
    autoDeploy: true
    rootDir: .